[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyckb"
version = "0.1.5"
authors = [
  { name="Mohanson", email="mohanson@outlook.com" },
]
description = "Python SDK for CKB"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["requests"]

[project.urls]
homepage = "https://github.com/mohanson/pyckb"
